version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    deploy:
      resources:
        limits:
          memory: 300M

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"  # 🔥 exposes Kafka to your host machine
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    deploy:
      resources:
        limits:
          memory: 512M

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading_data
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          memory: 400M

  kafka-consumer:
    build: ./kafka-consumer
    depends_on:
      - kafka
      - mysql
    deploy:
      resources:
        limits:
          memory: 256M
